-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE 'BETA';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "lastResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "monthlySecondsLimit" INTEGER NOT NULL DEFAULT 3600,
ADD COLUMN     "usedSeconds" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "role" SET DEFAULT 'BETA';
