-- AlterTable
ALTER TABLE "User" ADD COLUMN     "currentPeriodRemainingTime" INTEGER NOT NULL DEFAULT 1800,
ADD COLUMN     "currentPeriodUsedTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
